// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgftmsogceyfysbjqnnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnZnRtc29nY2V5ZnlzYmpxbm5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTk0MTcsImV4cCI6MjA2OTk5NTQxN30.4Vp9vu9pqSdbTPJs1waGAy6z6iirfrCervORZ_E1Dug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});